spring:
  application:
    name: batch-demo
  datasource:
    url: jdbc:h2:mem:batch
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  batch:
    job:
      enabled: false

server:
  port: 6070